version: '2'

services:
  hdfs:
    build: base
    volumes:
      - "./conf.docker_cluster:/etc/hadoop/conf:ro"
    user: hdfs
    entrypoint:
      - hdfs
    networks:
      - lagoon

networks:
  lagoon:
    external:
      name: hdp2-lagoon
